const { ethers } = require("hardhat");


const FEE_TOKEN_ADDRESS =  ""

const VOTING_ESCROW_ADDRESS =  ""

const DELEGATION_BOOST_ADDRESS =  ""

const FEE_RATIO = 500 // 5%

const MIN_PERCENT_REQUIRED = 1000 //10%


//Deploys

WARDEN_ADDRESS = ""

WARDEN_UTILS_ADDRESS = ""

module.exports = {
    FEE_TOKEN_ADDRESS,
    VOTING_ESCROW_ADDRESS,
    DELEGATION_BOOST_ADDRESS,
    FEE_RATIO,
    MIN_PERCENT_REQUIRED,
    WARDEN_ADDRESS,
    WARDEN_UTILS_ADDRESS,
};